- examples/yelp.js
Adopts new helper functions in yelp example and refactors source to be more readable / reusable.
https://replay.io/view?id=d853e5fa-400c-40ae-9584-15a1329bad72
Blocked by #29
> Refactor yelp example

- examples/espn.js
Refactor to use helpers and simplify selectors
https://replay.io/view?id=e4bf4826-bcf7-4a8c-b923-8b1cfea9bbea
(Replay is truncated :( )
> Refactor espn to use example helper

- examples/cypress.js
Refactor to use helper
https://replay.io/view?id=f2e26623-1ab1-45d4-9bb4-4113088ed260
> Refactor cypress example

- examples/climatescape.js
Minor refactor to use the example helper
> Refactor climatescape to use example helper

- examples/codepen.js
Adds an example with codepen that injects html/css/js and evaluates it.
https://replay.io/view?id=3096e81d-a49a-43a6-a606-2bfed6d98325
> Add codepen example

- examples/airbnb.js
- src/dom.js
- src/selectors.js
* Refactors Airbnb sample to use helpers
* Add price filtering
https://replay.io/view?id=98e41554-6e88-49d9-bc51-bbd0dd157983
> Refactor Airbnb example

- examples/firebugs.js
Basic refactoring and generalizing selectors
https://replay.io/view?id=0d100665-a62c-4120-91ee-07f5c07d8e72
> Refactor firebugs to use example helper and simplify selectors

- examples/notion.js
- src/dom.js
* Update notion example
* Adds `waitForTitleChange` to `dom.js`
https://replay.io/view?id=5ef7ff46-81a3-429c-b0f4-bc04a49ea52b
> Refactor notion example

- examples/nytimes.js
More refactoring!
https://replay.io/view?id=bf02ed22-136a-4d5e-96d1-2f4aa18ac1b9
> Refactor nytimes

- examples/replit.js
Other than manually handling the captcha, this test logs into replit, opens a project, updates it, and runs it.
https://replay.io/view?id=dcacea63-e100-42b6-8b97-a034d78c8cbe
> Add replit example

- examples/realadvisor.js
Refactor realadvisor example to use helper
https://replay.io/view?id=15b00729-ba6c-44be-ab80-1d76e5cda677
> Refactor realadvisor example

- examples/tablecheck.js
Refactor TableCheck sample to use new helper
https://replay.io/view?id=4fb98b54-368b-4445-a811-b6760d3dadef
> Refactor tablecheck

- examples/whatsmyuseragent.js
Not much to see here :)
https://replay.io/view?id=0c32c9f3-c0ba-46bd-931a-a3c17ef4c5ee
> Refactor whatismyuseragent to use example helper

- examples/reddit.js
Update reddit example to use the new helper. Changed the starting page to avoid loading timeout errors and added navigation to a subreddit to expand it a bit.
https://replay.io/view?id=8ee889b4-5746-4b48-af50-d30eb7622e04
> Refactor reddit example to use helper

- examples/unsplash.js
Refactor unsplash example to use helper and simplify selectors
https://replay.io/view?id=c99be186-8bd5-4c2e-9abf-c33583a9807f (replay is truncated)
> Refactor unsplash example

- examples/reactcharts.js
- src/dom.js
* Update reactcharts example
* Add `waitForFrameNavigated` utility method to aid some of the frames and frames in frames scenarios
https://replay.io/view?id=d30ccf10-2711-4e2c-bc95-2b54fc004b9e
> Refactor reactcharts example

- examples/replay.js
- src/helpers.js
* Refactors Replay sample
* Adds `step` method to helper for improved reporting:
```
> Replay
Browser launched
> Running example
Switch to Devtools
Select source
> Test breakpoints
Check breakpoint hits on line 11
Add breakpoint on line 20
Update breakpoint
< Test breakpoints
Jump to Hello 7
Switch to pause view
< Running example
< Replay
```
https://replay.io/view?id=67b6805b-4845-415b-9676-4ee3e257a071
> Refactor replay sample

- examples/ebay.js
Adds an ebay sample that:
* searches for iPhone
* Sorts by ending soonest,
* Selects the first result
* Views the seller's profile
* Views the seller's feedback
https://replay.io/view?id=a1f201ee-258d-49b9-bbd4-bccfad802bfc
Fixes #20
> Add Ebay sample

- examples/marko.js
- examples/monaco.js
- examples/shared/monaco.js
Adds a marko example that injects a simple component and runs it.
https://replay.io/view?id=67236430-c105-4300-aefd-cd54ab9b9af8
Fixes #44
> Add marko example

- examples/eraser.js
- examples/excalidraw.js
- examples/shared/excalidraw.js
* Adds Eraser example
* Refactor common excalidraw logic into shared module
https://replay.io/view?id=3acf6f52-658b-46bb-a068-14e312368024
Fixes #27 
Blocked by #68
> Add eraser sample

- examples/lit.js
Adds an example from the lit.dev playground
*NOTE:* - This currently crashes on firefox + replay but works in chromium
Fixes #62
> Add lit example

- .gitignore
- examples/airtable.js
- examples/framer.js
- examples/shared/google.js
- package-lock.json
- package.json
- run.ts
- src/helpers.js
- src/metadata.js
This adds an `uploadMetadata` function that saves the new recording to an existing workspace
> Add metadata

- examples/pixijs.js
- src/dom.js
Adds PixiJS Example
https://replay.io/view?id=940d3034-180a-47ad-a8a7-c0a268564308
Fixes #71
> Add PixiJS Example

- examples/shared/monaco.js
- examples/solid.js
* Adds SolidJS example
* Adds `addInput` method to shared monaco lib
https://replay.io/view?id=cec01082-c297-4c44-ab8e-0b54b03a1994
Fixes #43
> Add SolidJS Example

- test-manifest.js
> Import all qawolf/ tests into test manifest

- .github/workflows/qawolf-tests.yml
- qawolf-tests.js
- qawolf/helpers.js
The idea here is to record the qa wolf tests once a day. Ideally the tests would show up in our test suite dashboard so you could see how many passed/failed.
> QA Wolf test runer

- package-lock.json
- package.json
- scripts/env.ts
`npm start ./qawolf/name_of_test.js` will fetch QA wolf environment context, inject that into `process.env` and then `import()` the provided script to run it.
> Add env script to inject QA Wolf environment
